features_flow_config:
  features_list:
  - speed_minxlanes_minxseg_15min_num
  - speed_avgxlanes_diffprevrec_avgxseg_1hravg15min_num
  - speedstd_maxxlanes_maxxseg_1hrmax15min_num
  - speed_avgxlanes_maxxseg_1hravg15min_num
  - speed_avgxlanes_diffloopbehind_maxxseg_15min_num
  - flowstd_avgxlanes_avgxseg_15min_num
  - speed_avgxlanes_diffloopbehind_avgxseg_1hrmax15min_num
  - flow_totalxlanes_diffprevrec_maxxseg_1hravg15min_num
  - flow_totalxlanes_maxdiffxseg_15min_num
  - speed_avgxlanes_diffloopahead_maxxseg_15min_num
  - speed_avgxlanes_diffprevrec_maxxseg_15min_num
  - flow_totalxlanes_totalxseg_1hrmin15min_num
  - flow_totalxlanes_totalxseg_maxdiffx1hr_num
  - speed_avgxlanes_diffloopahead_avgxseg_1hravg15min_num
  - flow_totalxlanes_diffprevrec_maxxseg_15min_num
  - speed_avgxlanes_diffprevrec_avgxseg_15min_num
  - speed_avgxlanes_diffprevrec_avgxseg_1hrmax15min_num
  - flow_totalxlanes_diffprevrec_avgxseg_1hravg15min_num
  - flow_totalxlanes_diffprevrec_avgxseg_15min_num
  - flow_totalxlanes_diffloopbehind_maxxseg_1hravg15min_num
  - flow_avgxlanes_minxseg_15min_num
  - speed_maxdiffxlanes_maxxseg_15min_num
  - flow_totalxlanes_diffloopbehind_avgxseg_1hrmax15min_num
  - speed_avgxlanes_maxxseg_maxdiffx1hr_num
  - flow_totalxlanes_diffloopahead_avgxseg_1hravg15min_num
  - speed_maxdiffxlanes_avgxseg_1hrmax15min_num
  meta_columns:
  - end_datetime
  - hectokey_merged
  space_granularity_km: 10
  table_name: features_speedflow_agg.fifteenmin_seg_ten_km_v1
  time_granularity_min: 15
  use_all_features: false
features_hectopunten_config:
  features_list:
  - asphalt_age_avgxseg_num
  - onramps_convergentie_or_bstcodeopr_totalxseg_num
  - trees_within50m_avgxseg_num
  - onramps_convergentie_or_bstcodeopr_perkm_num
  - max_number_lanes_avgxseg_num
  meta_columns:
  - hectokey_merged
  - rollup_year
  - weather_station
  space_granularity_km: 10
  table_name: features_hectopunten_agg.hectopunten_ten_km_v12
  use_all_features: false
features_knmi_config:
  features_list:
  - feature_last_snow_num
  - feature_last_ice_num
  - feature_last_thunderstorm_num
  - feature_temp_16_mean_num
  - feature_air_pressure_16_nanmax_num
  - feature_humidity_8_nanmin_num
  - feature_last_mist_num
  - feature_humidity_1_ago_num
  - feature_observability_16_mean_num
  - feature_sun_duration_16_mean_num
  - feature_last_rain_num
  - feature_humidity_8_nanmax_num
  - feature_humidity_16_nanmax_num
  - feature_precip_duration_16_mean_num
  meta_columns:
  - datetime
  - weather_station
  table_name: features_knmi_agg.knmi_feature_master_v7
  time_granularity_min: 60
  use_all_features: false
features_ongevallen_config:
  features_list:
  - accidents_past_16_num
  - accidents_past_1_num
  meta_columns:
  - datetime
  - hectokey_merged
  space_granularity_km: 10
  table_name: features_ongevallen_agg.ongevallen_feature_ten_km_thirty_min
  time_granularity_min: 30
  use_all_features: false
features_temporal_config:
  features_list:
  - rushhour_cat
  - eve_rushhour_cat
  - month_cat
  meta_columns:
  - datetime
  table_name: features_temporal_agg.temporal_feature_60min_v3
  time_granularity_min: 60
  use_all_features: false
