panel_config:
  time_granularity: 60
  segmentation_table: "segmentation.five_km"
  weather_station_mapping_table: "segmentation.five_km_ws"
  time_lag_minutes: 0
  sample_train: True
  sample_val: True
  sample_test: True
  train_sample_method_params:
    sampling_method: "random"
    positive_perc: 0.15
  val_sample_method_params:
    sampling_method: "full"
    positive_perc : 0.03
  test_sample_method_params:
    sampling_method: "full"
    positive_perc: 0.04
  validation_config:
    label_start: "2016-01-01"
    label_end: "2017-12-31"
    test_start: "2018-01-01"
    test_end: "2018-01-31"
    minimum_gap_size:
      months: 1
    rolling_type: "window"
    minimum_train_size:
      years: 1
    minimum_val_size:
      months: 1
  random_seed: 42
  exp_remarks: "configurations to test how many features to use in main experiments"

classifier_config:
  - XG
  - BASE_RANDOM
  - BASE_SMART

grid_config:
  XG:
    scale_pos_weight:
      - 1
      - 20
    max_depth:
      - 4
      - 8
      - 16
    min_child_weight:
      - 6
      - 8
    learning_rate:
      - 0.1
    n_estimators:
      - 300
      - 400
      - 500
    reg_alpha:
      - 0.001
      - 0.1
  BASE_RANDOM:
    random_state:
      - 42
  BASE_SMART:
     n_estimators:
      - 1
      
   